### ISSUE TITLE
multiple pwm instances break functionality

### ISSUE THREAD

**Issue by tacoe** [johntreacy/adafruit-pca9685#1]
If you chain PCA9685s, creating multiple instances of a pwm object results in buggy behavior (eg with two chained banks, bank #2 gets distorted PWM values, bank #1 doesn't work at all). Not sure if this is as intended, but thought it worthwhile to mention.

**Comment by johntreacy** [comment]
Can you tell me more about this setup? Do you have any test code that you could share?

**Comment by johntreacy** [comment]
I reproduced the problem today and I believe I have found the issue and a fix. Expect an update soon after some more testing.

**Comment by johntreacy** [comment]
Fixed in main branch. Objects that should not have been reused were. Oops. Tested with two PCA9685, one at address 0x40 and one at 0x41.
